### ISSUE TITLE
Improve support for include directive

### ISSUE THREAD

**Issue by yegle** [aumayr/beancount-web#9]
It looks like the tool doesn't handle included files properly. Here's a minimal test case that demonstrate the problem.

invest.bean
```
include "accounts.bean"
include "a.bean"
include "b.bean"
```

accounts.bean
```
2015-12-09 open Assets:AccountA
2015-12-09 open Assets:AccountB
```

a.bean
```
include "accounts.bean"

2015-12-09 *
    Assets:AccountA -1 USD
    Assets:AccountB 1 USD
```

b.bean
```
include "accounts.bean"

2015-12-10 *
    Assets:AccountA -1 USD
    Assets:AccountB 1 USD
```

Run `beancount-web invest.bean` there's no error (except for the benign warning because `accounts.bean` was included twice), but there's no balance shown on the start page.

Use `bean-report -f beancount invest.bean print > /tmp/output.beancount` to `concatenate` everything into a single file, beancount-web works again.

**Comment by aumayr** [comment]
I found the source for the missing values: `beancount.loader.load_file` does return a wrong `options_map`. 

I filed a bug with `beancount` here: [blais/beancount/issues/91](https://bitbucket.org/blais/beancount/issues/91/options_map-misses-entries-from-multiple)

As soon as this is fixed in `beancount`-core it will work properly in `beancount-web`.

**Comment by aumayr** [comment]
Martin fixed this yesterday in `beancount` ([changeset](https://bitbucket.org/blais/beancount/commits/ca4619ab2792c8a922d4fa15384f92fcc7c02b2d?at=default))

And I also changed `beancount-web` to display ZERO-values (current HEAD: 348f9fb5d6cd11d68b4f8e883a84307f989e0dbb)

@yegle Does it work now as expected?

**Comment by yegle** [comment]
Yes the fix in beancount does solve my problem.

However I still don't see the chart (I suspected this issue is the reason of no chart, but apparently that's not the case...). Maybe I should file another bug?

**Comment by aumayr** [comment]
That's because charts are only shown for operating currencies.

Try to add `option "operating_currency" "USD"` in your `invest.bean`, then the charts for `USD`-positions should be displayed correctly.

**Comment by yegle** [comment]
Ah, thanks. This is not immediately obvious to me. Maybe some warning on the chart so people know that?

**Comment by aumayr** [comment]
Yep, created #23 and #24 to track those enhancements. Thanks for the feedback!
